### PR TITLE
Rework: Add integration testing. Filters: geoip, dns, translate. DHCP

### PR DESCRIPTION
**Pull request by ypid**
* Add integration testing
* Add parser for DHCPv4 logs
* Use Logstash filters: geoip, dns
* Support to translate interface internal names to description defined
  by the admin using the Logstash translate filters
  A script is provided to generate the mapping from an OPNsense backup
  XML file.

Note that I have not tested all log types carefully. I only mainly use filterlog. Please add more tests.

Tested on: Logstash 6.2.4.
Closes: https://github.com/fabianfrz/opnsense-logstash-config/pull/3

### CODE REVIEW

**Comment by fabianfrz** [comment]
This has many issues and can not be merged because of that:

* contains a git submodule -> this project should be as easy as possible - download, copy and done
* contains AGPL code which is incompatible - because of that, this PR has to be rejected.
* contains Python 3 code -> the project runs on logstash, which is jruby

**Comment by ypid** [comment]
> contains a git submodule -> this project should be as easy as possible - download, copy and done

For that use case, just ignore the submodule. It still works. The reason git submodules are used is to avoid duplicating code into all repos which use the test environment. You have used git submodules before and know how they work? Anything wrong with that?

You did not say anything about if you find a test environment useful. I would never write complex filter statements (like the one you provided) without one. Would you agree?

> contains AGPL code which is incompatible

The script is not essential, it is just a helper. It is entirely optional, if you either have not many interfaces or enjoy to do manual copy pasting work and don’t accept being replaced by "a small Shell/Python" script then just ignore the script. You can without issues include the script here when you have a `LICENSE` file saying something else. Everything else where no explicit license was choose by me I am fine with your default one. If it makes you happy, I will relicense it to MIT only.

> contains Python 3 code -> the project runs on logstash, which is jruby

See previous comment: "The script is not essential"

**Comment by fabianfrz** [comment]
Sorry, cannot merge that - it is really not what I want. For me there are the issues mentioned above and I really don't like the structure - especially also the split config. If this is the right direction for you, you may be interested in a detached fork because the code will probably never be merged together.

**Comment by ypid** [comment]
I wanted to give it a try to join forces but the decision is up to you. The split config is not some random decision but comes from my day job where colleagues and me run Logstash with a complexer configuration in production for almost a year now. Note that this work on opnsense-logstash-config is completely done in my spare time and has no relation to my work.

I don’t really like forks when it can be avoided. Can you tell me something about your deployment? How can you ensure that your config still works when you change something? Still, you have not said anything about integration testing and my other questions.

**Comment by fabianfrz** [comment]
Maybe a better idea would be running a logstash instance, send the input to the syslog port and emulate a server (tcp or elasticsearch), which just evaluates it if it is the expected data structure. In that case, no files are required. In that case it would also keep the repository clean, because it would be only one ruby file and a JSON document (with input and the expected result).

This project proably does not really have a lot of structure but it should be a single conf that can just be copied and then adjusted (for example changing the output to something else). After that it should run using a single command like logstash like `/usr/share/logstash/logstash-core/versions-gem-copy.yml -f opnsense.conf`. This does not only ease development, it also works pretty well with systemd because you can run instances for different services like that: `systemctl start logstash@opnsense` which will look for `opnsense.conf` in a special directory.

**Comment by ypid** [comment]
Thanks for your feedback. I don’t like this approach of integration testing for the following reasons:

* In complex deployments, your inputs and outputs will be different for test and production anyway, so having them in separate files allows to build your production config straight from the test env (script and rsync config included in the submodule). For example, in real production you would probably not send opnsense logs directly to Logstash but instead use either a queuing system or the more classical approach if you already have a syslog host in place where you then read the logs files with Logstash. This has many advantages: Dealing with logging peaks, allowing to reimport logs to Elasticsearch when you change the filter, long term archive of compressed log files on the syslog server, no log gaps when restarting Logstash, …
Same goes for the output, in test, having an Elasticsearch without authentication is perfectly fine, in production, you don’t want that.
* I don’t want to test Logstash itself but mainly my filter configuration because that is usually the most complex. For this, using unix sockets as input and files as output appeared to be the most straight forward way. I just expect Logstash has unit/integration tests for testing their plugins.

Because of that, it would make sense to move the dns and geoip part to a separate file.

To your second point: This is probably nice when you only have a few log or other input types. But in bigger deployments you will find many different log input types all needing their own filters. Some of those types might share some filter blocks. Good luck doing that with one file for each pipeline.
Also, Logstash 6.0 introduced support for multiple pipelines which I would prefer over multiple Logstash instances. You can still have multiple Logstash instances for different security zones (internal and DMZ for example), but then they would be isolated on different VMs and hosts anyway.

PS: If we end up with a fork, maybe just add a ref to my project, I will do the same in my readme.

**Comment by ypid** [comment]
> If we end up with a fork, maybe just add a ref to my project, I will do the same in my readme.

Added.

**Pull request closed without merging**
